# Generated by Django 2.1.2 on 2018-11-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedorganization',
            old_name='organization_name',
            new_name='join_as',
        ),
    ]
