# Generated by Django 2.1.2 on 2018-11-02 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('institute', models.CharField(blank=True, max_length=120, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('last_donation_place', models.CharField(blank=True, max_length=50, null=True)),
                ('donation_capability', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('donation_times', models.IntegerField()),
                ('facebook_link', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor_profile.BloodGroupName')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
